// Maps ISO 3166-1 alpha-2 codes (what CDN geo headers like `cf-ipcountry` and
// `x-vercel-ip-country` return) to the ISO 3166-1 numeric id used as the feature
// `id` in the world-atlas countries-110m TopoJSON the map renders. Also carries
// the English name for tooltips. Used to colour the "Popular Countries" map by
// bot usage.

export type IsoCountry = { numeric: string; name: string };

// alpha-2 -> { numeric id (as string, matches geo.id), display name }
export const ISO_COUNTRIES: Record<string, IsoCountry> = {
  AF: { numeric: "004", name: "Afghanistan" },
  AL: { numeric: "008", name: "Albania" },
  DZ: { numeric: "012", name: "Algeria" },
  AO: { numeric: "024", name: "Angola" },
  AR: { numeric: "032", name: "Argentina" },
  AM: { numeric: "051", name: "Armenia" },
  AU: { numeric: "036", name: "Australia" },
  AT: { numeric: "040", name: "Austria" },
  AZ: { numeric: "031", name: "Azerbaijan" },
  BS: { numeric: "044", name: "Bahamas" },
  BD: { numeric: "050", name: "Bangladesh" },
  BY: { numeric: "112", name: "Belarus" },
  BE: { numeric: "056", name: "Belgium" },
  BZ: { numeric: "084", name: "Belize" },
  BJ: { numeric: "204", name: "Benin" },
  BT: { numeric: "064", name: "Bhutan" },
  BO: { numeric: "068", name: "Bolivia" },
  BA: { numeric: "070", name: "Bosnia and Herzegovina" },
  BW: { numeric: "072", name: "Botswana" },
  BR: { numeric: "076", name: "Brazil" },
  BN: { numeric: "096", name: "Brunei" },
  BG: { numeric: "100", name: "Bulgaria" },
  BF: { numeric: "854", name: "Burkina Faso" },
  BI: { numeric: "108", name: "Burundi" },
  KH: { numeric: "116", name: "Cambodia" },
  CM: { numeric: "120", name: "Cameroon" },
  CA: { numeric: "124", name: "Canada" },
  CF: { numeric: "140", name: "Central African Republic" },
  TD: { numeric: "148", name: "Chad" },
  CL: { numeric: "152", name: "Chile" },
  CN: { numeric: "156", name: "China" },
  CO: { numeric: "170", name: "Colombia" },
  CG: { numeric: "178", name: "Congo" },
  CD: { numeric: "180", name: "Dem. Rep. Congo" },
  CR: { numeric: "188", name: "Costa Rica" },
  CI: { numeric: "384", name: "Côte d'Ivoire" },
  HR: { numeric: "191", name: "Croatia" },
  CU: { numeric: "192", name: "Cuba" },
  CY: { numeric: "196", name: "Cyprus" },
  CZ: { numeric: "203", name: "Czechia" },
  DK: { numeric: "208", name: "Denmark" },
  DJ: { numeric: "262", name: "Djibouti" },
  DO: { numeric: "214", name: "Dominican Republic" },
  EC: { numeric: "218", name: "Ecuador" },
  EG: { numeric: "818", name: "Egypt" },
  SV: { numeric: "222", name: "El Salvador" },
  GQ: { numeric: "226", name: "Equatorial Guinea" },
  ER: { numeric: "232", name: "Eritrea" },
  EE: { numeric: "233", name: "Estonia" },
  SZ: { numeric: "748", name: "Eswatini" },
  ET: { numeric: "231", name: "Ethiopia" },
  FJ: { numeric: "242", name: "Fiji" },
  FI: { numeric: "246", name: "Finland" },
  FR: { numeric: "250", name: "France" },
  GA: { numeric: "266", name: "Gabon" },
  GM: { numeric: "270", name: "Gambia" },
  GE: { numeric: "268", name: "Georgia" },
  DE: { numeric: "276", name: "Germany" },
  GH: { numeric: "288", name: "Ghana" },
  GR: { numeric: "300", name: "Greece" },
  GL: { numeric: "304", name: "Greenland" },
  GT: { numeric: "320", name: "Guatemala" },
  GN: { numeric: "324", name: "Guinea" },
  GW: { numeric: "624", name: "Guinea-Bissau" },
  GY: { numeric: "328", name: "Guyana" },
  HT: { numeric: "332", name: "Haiti" },
  HN: { numeric: "340", name: "Honduras" },
  HU: { numeric: "348", name: "Hungary" },
  IS: { numeric: "352", name: "Iceland" },
  IN: { numeric: "356", name: "India" },
  ID: { numeric: "360", name: "Indonesia" },
  IR: { numeric: "364", name: "Iran" },
  IQ: { numeric: "368", name: "Iraq" },
  IE: { numeric: "372", name: "Ireland" },
  IL: { numeric: "376", name: "Israel" },
  IT: { numeric: "380", name: "Italy" },
  JM: { numeric: "388", name: "Jamaica" },
  JP: { numeric: "392", name: "Japan" },
  JO: { numeric: "400", name: "Jordan" },
  KZ: { numeric: "398", name: "Kazakhstan" },
  KE: { numeric: "404", name: "Kenya" },
  KW: { numeric: "414", name: "Kuwait" },
  KG: { numeric: "417", name: "Kyrgyzstan" },
  LA: { numeric: "418", name: "Laos" },
  LV: { numeric: "428", name: "Latvia" },
  LB: { numeric: "422", name: "Lebanon" },
  LS: { numeric: "426", name: "Lesotho" },
  LR: { numeric: "430", name: "Liberia" },
  LY: { numeric: "434", name: "Libya" },
  LT: { numeric: "440", name: "Lithuania" },
  LU: { numeric: "442", name: "Luxembourg" },
  MG: { numeric: "450", name: "Madagascar" },
  MW: { numeric: "454", name: "Malawi" },
  MY: { numeric: "458", name: "Malaysia" },
  ML: { numeric: "466", name: "Mali" },
  MR: { numeric: "478", name: "Mauritania" },
  MX: { numeric: "484", name: "Mexico" },
  MD: { numeric: "498", name: "Moldova" },
  MN: { numeric: "496", name: "Mongolia" },
  ME: { numeric: "499", name: "Montenegro" },
  MA: { numeric: "504", name: "Morocco" },
  MZ: { numeric: "508", name: "Mozambique" },
  MM: { numeric: "104", name: "Myanmar" },
  NA: { numeric: "516", name: "Namibia" },
  NP: { numeric: "524", name: "Nepal" },
  NL: { numeric: "528", name: "Netherlands" },
  NZ: { numeric: "554", name: "New Zealand" },
  NI: { numeric: "558", name: "Nicaragua" },
  NE: { numeric: "562", name: "Niger" },
  NG: { numeric: "566", name: "Nigeria" },
  KP: { numeric: "408", name: "North Korea" },
  MK: { numeric: "807", name: "North Macedonia" },
  NO: { numeric: "578", name: "Norway" },
  OM: { numeric: "512", name: "Oman" },
  PK: { numeric: "586", name: "Pakistan" },
  PS: { numeric: "275", name: "Palestine" },
  PA: { numeric: "591", name: "Panama" },
  PG: { numeric: "598", name: "Papua New Guinea" },
  PY: { numeric: "600", name: "Paraguay" },
  PE: { numeric: "604", name: "Peru" },
  PH: { numeric: "608", name: "Philippines" },
  PL: { numeric: "616", name: "Poland" },
  PT: { numeric: "620", name: "Portugal" },
  QA: { numeric: "634", name: "Qatar" },
  RO: { numeric: "642", name: "Romania" },
  RU: { numeric: "643", name: "Russia" },
  RW: { numeric: "646", name: "Rwanda" },
  SA: { numeric: "682", name: "Saudi Arabia" },
  SN: { numeric: "686", name: "Senegal" },
  RS: { numeric: "688", name: "Serbia" },
  SL: { numeric: "694", name: "Sierra Leone" },
  SG: { numeric: "702", name: "Singapore" },
  SK: { numeric: "703", name: "Slovakia" },
  SI: { numeric: "705", name: "Slovenia" },
  SB: { numeric: "090", name: "Solomon Islands" },
  SO: { numeric: "706", name: "Somalia" },
  ZA: { numeric: "710", name: "South Africa" },
  KR: { numeric: "410", name: "South Korea" },
  SS: { numeric: "728", name: "South Sudan" },
  ES: { numeric: "724", name: "Spain" },
  LK: { numeric: "144", name: "Sri Lanka" },
  SD: { numeric: "729", name: "Sudan" },
  SR: { numeric: "740", name: "Suriname" },
  SE: { numeric: "752", name: "Sweden" },
  CH: { numeric: "756", name: "Switzerland" },
  SY: { numeric: "760", name: "Syria" },
  TW: { numeric: "158", name: "Taiwan" },
  TJ: { numeric: "762", name: "Tajikistan" },
  TZ: { numeric: "834", name: "Tanzania" },
  TH: { numeric: "764", name: "Thailand" },
  TL: { numeric: "626", name: "Timor-Leste" },
  TG: { numeric: "768", name: "Togo" },
  TT: { numeric: "780", name: "Trinidad and Tobago" },
  TN: { numeric: "788", name: "Tunisia" },
  TR: { numeric: "792", name: "Turkey" },
  TM: { numeric: "795", name: "Turkmenistan" },
  UG: { numeric: "800", name: "Uganda" },
  UA: { numeric: "804", name: "Ukraine" },
  AE: { numeric: "784", name: "United Arab Emirates" },
  GB: { numeric: "826", name: "United Kingdom" },
  US: { numeric: "840", name: "United States" },
  UY: { numeric: "858", name: "Uruguay" },
  UZ: { numeric: "860", name: "Uzbekistan" },
  VU: { numeric: "548", name: "Vanuatu" },
  VE: { numeric: "862", name: "Venezuela" },
  VN: { numeric: "704", name: "Vietnam" },
  YE: { numeric: "887", name: "Yemen" },
  ZM: { numeric: "894", name: "Zambia" },
  ZW: { numeric: "716", name: "Zimbabwe" },
};

// Normalizes/validates a CDN header value into a stored alpha-2 code, or null.
// CDNs use "XX"/"T1" for unknown/Tor — treat those as no-country.
export function normalizeCountryCode(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const code = raw.trim().toUpperCase();
  if (code.length !== 2) return null;
  if (code === "XX" || code === "T1") return null;
  return ISO_COUNTRIES[code] ? code : null;
}
