#!/bin/bash

# Script to extract Firebase config from GoogleService-Info.plist and update firebase_options.dart

PLIST_FILE="ios/Runner/GoogleService-Info.plist"
OPTIONS_FILE="lib/firebase_options.dart"

echo "🔍 Extracting Firebase configuration from GoogleService-Info.plist..."

if [ ! -f "$PLIST_FILE" ]; then
    echo "❌ Error: GoogleService-Info.plist not found at $PLIST_FILE"
    exit 1
fi

# Extract values using grep and sed
API_KEY=$(grep -A 1 "<key>API_KEY</key>" "$PLIST_FILE" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
APP_ID=$(grep -A 1 "<key>GOOGLE_APP_ID</key>" "$PLIST_FILE" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
SENDER_ID=$(grep -A 1 "<key>GCM_SENDER_ID</key>" "$PLIST_FILE" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
PROJECT_ID=$(grep -A 1 "<key>PROJECT_ID</key>" "$PLIST_FILE" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
BUNDLE_ID=$(grep -A 1 "<key>BUNDLE_ID</key>" "$PLIST_FILE" | grep "<string>" | sed 's/.*<string>\(.*\)<\/string>.*/\1/')

echo "✅ Extracted values:"
echo "   API_KEY: ${API_KEY:0:20}..."
echo "   APP_ID: ${APP_ID:0:30}..."
echo "   SENDER_ID: $SENDER_ID"
echo "   PROJECT_ID: $PROJECT_ID"
echo "   BUNDLE_ID: $BUNDLE_ID"

# Create firebase_options.dart with extracted values
cat > "$OPTIONS_FILE" << EOF
// File generated by extract_firebase_config.sh
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$API_KEY',
    appId: '$APP_ID',
    messagingSenderId: '$SENDER_ID',
    projectId: '$PROJECT_ID',
    storageBucket: '$PROJECT_ID.appspot.com',
    iosBundleId: '$BUNDLE_ID',
  );
}
EOF

echo "✅ Updated $OPTIONS_FILE with Firebase configuration"
echo ""
echo "🎉 Done! Now you can build and run your app:"
echo "   flutter clean"
echo "   flutter pub get"
echo "   cd ios && pod install && cd .."
echo "   flutter run"
